spring:
  redis:
    host: 47.99.108.112
    port: 6379
    password: dzyx6379cz
    database: 0
    lettuce:
      pool:
        max-active: 16
        max-idle: 8
        min-idle: 0


logback:
  home: /Users/ward/Desktop/logs/${spring.application.name}
