spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 16
        max-idle: 8
        min-idle: 0
  datasource:
    url: jdbc:mysql://47.99.33.229:3307/aierbon?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: dzyxuser
    password: mysql2015CZ
rocketmq:
  #mq的nameserver地址
  name-server: 127.0.0.1:9876

clientcache:
  keyConfigs:
    "[student _ _ ? _]":
      - "/student-service/test.* _ _ q _"
    "[leave _ _ _ leaveId]":
      - "/student-service/test.* _ _ _ s"