spring:
  redis:
    host: 47.99.33.229
    port: 12379
    password: Dazhi100
    database: 0
    lettuce:
      pool:
        max-active: 32
        max-wait: 300ms
        max-idle: 16
        min-idle: 2
  datasource:
    url: jdbc:mysql://47.99.33.229:3307/student?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: dzyxuser
    password: mysql2015CZ
rocketmq:
  #mq的nameserver地址
  name-server: 127.0.0.1:9876

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    enabled: true