version: "3"
services:
  student:
    hostname: student
    image: 172.16.56.117:18090/dzyx/student-web:latest
    container_name: student-web
    restart: always
    ports:
      - "6081:6081"
    networks:
      - dzyx-server-network

networks:
  dzyx-server-network:
    external: false
